version: 2.1

orbs:
  node: circleci/node@4.1.0
  gcp-cli: circleci/gcp-cli@3.1.0  # Please replace x.y.z with the correct version

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-dependencies
      - build-app:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - build-app

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - save_cache:
          key: 'npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules

  build-app:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: 'npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
      - run:
          name: Build React app
          command: |
            npm run build
      - run:
          name: Name the build with the SHA
          command: |
            echo "Build SHA: ${CIRCLE_SHA1}" > build/SHA.txt
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - gcp-cli/install
      - run:
          name: Auth with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - gcp-cli/initialize
      - attach_workspace:
          at: .
      - run:
          name: Upload and Deploy to GCP
          command: |
            gsutil cp -r build gs://jeffreyo3-portfolio
            gcloud app deploy --quiet
