version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build React App
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - build
